### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by HaNdTriX** [HaNdTriX/webextension-toolbox#15]
More info: https://github.com/HaNdTriX/generator-web-extension/issues/9

**Comment by balcsida** [comment]
I've experienced issues on Windows as well, I will try to take a look on this.

**Comment by HaNdTriX** [comment]
Awesome thanks 🙏

**Comment by balcsida** [comment]
It seems that the problem is in the path handling. Will dig deeper, just wanted to document my progress.
```
(node:42484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:42484) UnhandledPromiseRejectionWarning: Error: absolute path: C:/Users/balcs/Documents/GitHub/TESTPROJECT/node_modules/webextension-toolbox/src/auto-reload.js
    at validateMetadataPath (C:\Users\balcs\Documents\GitHub\TESTPROJECT\node_modules\yazl\index.js:351:74)
    at ZipFile.addBuffer (C:\Users\balcs\Documents\GitHub\TESTPROJECT\node_modules\yazl\index.js:62:18)
    at C:\Users\balcs\Documents\GitHub\TESTPROJECT\node_modules\zip-webpack-plugin\index.js:46:12
    at _err0 (eval at create (C:\Users\balcs\Documents\GitHub\TESTPROJECT\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:12:1)
    at callback (C:\Users\balcs\Documents\GitHub\TESTPROJECT\node_modules\copy-webpack-plugin\dist\index.js:77:17)
    at C:\Users\balcs\Documents\GitHub\TESTPROJECT\node_modules\copy-webpack-plugin\dist\index.js:118:24
    at <anonymous>
(node:42484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by balcsida** [comment]
Unfortunately this only caused by the ZIP module. Running 'dev' still hangs after webpack-clean.

**Comment by HaNdTriX** [comment]
Hmm that is weird, since the ZIP module should be disabled in dev mode.
In devmode (`webextension dev chrome`) we should not use packed extensions. https://github.com/HaNdTriX/webextension-toolbox/blob/next/src/webpack-config.js#L177-L182

Does the bug also appear in the new beta Version? If yes can you add the new Error msg?

**Comment by balcsida** [comment]
I will have time to try out the latest beta version, hopefully, with promising results.

**Comment by HaNdTriX** [comment]
@balcsida 

> Currently, I'm unable to npm install because I am getting this error:

It should have been fixed in the last beta.5 release.

> It seems that the problem is in the path handling. Will dig deeper, just wanted to document my progress.

Good news I found the itch. Nevertheless I need some time to do the PR.
Hopefully on monday we will have this finally fixed. Thanks for bringing me on the right track!

https://github.com/Milanzor/webpack-watched-glob-entries-plugin/blob/master/index.js#L88-L101

**Comment by HaNdTriX** [comment]
https://github.com/Milanzor/webpack-watched-glob-entries-plugin/pull/7

**Comment by balcsida** [comment]
Thank you! I didn't have time and knowledge to find this. Did you try it on a Windows machine by the chance?

**Comment by HaNdTriX** [comment]
Yes, I used a VM for that.

**Comment by balcsida** [comment]
Hmm, it seems that if I ´dev chrome´ on Windows cmd/PowerShell, ES6 modules does not work and somehow WebExt polyfills does not applied either...
From Ubuntu, it works fine

**Comment by balcsida** [comment]
Okay, it seems that this is only occurs when webpack is trying to inject webextension-polyfill.
For Ubuntu, the path separators are correct. E.g:
```
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! /usr/lib/node_modules/webextension-toolbox/node_modules/webextension-polyfill/dist/browser-polyfill.js */ "../../../../usr/lib/node_modules/webextension-toolbox/node_modules/webextension-polyfill/dist/browser-polyfill.js")))
```

However, on Windows, it looks like this:
```
/* WEBPACK VAR INJECTION */}.call(this, __webpack_require__(/*! C:/Users/balcs/AppData/Roaming/npm/node_modules/webextension-toolbox/node_modules/webextension-polyfill/dist/browser-polyfill.js */ "../../Users/balcs/AppData/Roaming/npm/node_modules/webextension-toolbox/node_modules/webextension-polyfill/dist/browser-polyfill.js")))
```

**Comment by HaNdTriX** [comment]
Can you try to delete your modules and reinstall them a gain.
I had an issue regarding the beta versions.

```bash
rm -r node_modules
rm package-lock.json
npm install
```

**Comment by HaNdTriX** [comment]
Good catch! I just fixed this issue in Version `webextension-toolbox@beta.7`.

https://github.com/HaNdTriX/webextension-toolbox/commit/285811e6789f1a71b23bd17459669fc9b368adb3

I didn't know, that the loaders have different paths as well. Lessons Learned! 😜

**Comment by balcsida** [comment]
Hi!

I've tested beta 7 with the sample extension and with a more complicated (meaning: full of import-export and browser APIs) and now it works as expected under Chrome and Opera.

Thank you, great job! 🙂
