### ISSUE TITLE
Support for SCSS and TS.

### ISSUE THREAD

**Issue by jkodu** [HaNdTriX/webextension-toolbox#17]
Great toolbox. Thanks for the hardwork.
Would it be possible to add your own loaders to the webpack config?
Need to add scss-loader and or ts-loader.

Thanks again.

**Comment by HaNdTriX** [comment]
We are planning a configuration option for this in the next mayor release. Please check out https://github.com/HaNdTriX/webextension-toolbox/pull/18 for the progress on that.

**Comment by jkodu** [comment]
Excellent thanks :) Looks good.

**Comment by HaNdTriX** [comment]
Good news! I just released the `webextension-toolbox@1.0.0-beta.1` Version.
If you want to play around with it install it via:

```bash
npm i webextension-toolbox@next
```
