### ISSUE TITLE
[Idea] Move example(s) to separate repo(s)

### ISSUE THREAD

**Issue by balcsida** [HaNdTriX/webextension-toolbox#20]
Maybe even create an organization for all of the webextension-toolbox related repo?

**Comment by HaNdTriX** [comment]
Organization sounds good but I prefer a monorepo instead.
A monorepo is much easier to manage and not as much work.

* https://lernajs.io/
* Example [babel](https://github.com/babel/babel)
* Example [create-react-app](https://github.com/facebook/create-react-app)

**Comment by balcsida** [comment]
That's okay, but is it possible to leave the examples folder out with an .npmignore?

**Comment by balcsida** [comment]
Ohh, ignore this completely, I feel really dumb. :|
