### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by qgerome** [HaNdTriX/webextension-toolbox#8]
Hello,

I'm trying to write a component in JSX but I receive an error:

```
ERROR in ./app/components/PopupApp.jsx
Module parse failed: Unexpected token (3:24)
You may need an appropriate loader to handle this file type.
| import React from 'react'
| 
| export default props => <h1></h1>

```
 
Do you know why it does not support JSX despite the presence of the babel preset "react" in the webpack configuration ?

**Comment by HaNdTriX** [comment]
Thank you for your feedback. 

I just fixed this issue in version `0.0.9`. If your issue is not resolved please reopen!
