### ISSUE TITLE
Chalk is an implicit dependency (should be explicit)

### ISSUE THREAD

**Issue by kachkaev** [HaNdTriX/webextension-toolbox#835]
👋 folks! Great library! 💯  I’ve noticed one edge case and have decided to share it.

[Chalk](https://www.npmjs.com/package/chalk) is used in `command.ts`:

https://github.com/webextension-toolbox/webextension-toolbox/blob/1b6482f08afe56b337027b7f493ce5d209c61762/src/command.ts#L2

However, it is not listed as a dependency in `package.json`. When a project depends on chalk v5+ ([which is pure ESM](https://github.com/chalk/chalk/releases/tag/v5.0.0)), import of chalk fails. It is attempted to be imported as CommonJS from `dist/command.js`, but only ESM is available. This causes Node.js to crash with `ERR_REQUIRE_ESM`. 

## Expected Behavior

A specific major version of chalk is mentioned in `package.json`, so the right copy of this dependency is resolved when webextension-toolbox is called. If it’s v5 (ESM), a built version `command.ts` is using an async import or is using ESM itself.

## Current Behavior

A ‘random’ version of chalk is picked, depending of the downstream project’s dependency tree. If that is v4 or less, then everything works. If that is v5.0.0 or greater, the tool crashes.

## Steps to Reproduce (for bugs)

Happy to provide these a bit later if needed

1.
2.
3.
4.

## Context

Trying to run `webextension-toolbox build`

## Your Environment

| Tech                    | Version |
|-------------------------|---------|
| webextension-toolbox    |  6.2.0 |
| node                    |  18.8.2  |
| OS                      |  macos    |

**Comment by tm1000** [comment]
This is resolved in: https://github.com/webextension-toolbox/webextension-toolbox/pull/832
